# Generated by Django 5.2.6 on 2025-09-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(help_text='The actual prompt text or blob.')),
                ('format', models.CharField(choices=[('plain', 'Plain Text'), ('json', 'JSON'), ('xml', 'XML')], default='plain', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
