# Generated by Django 5.2.6 on 2025-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVoteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.IntegerField(unique=True)),
                ('up_count', models.IntegerField(default=0)),
                ('down_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['prompt_id'], name='promptcente_prompt__235d6c_idx')],
            },
        ),
    ]
