# Generated by Django 5.2.6 on 2025-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptcenter', '0002_promptvotecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt',
            field=models.TextField(blank=True, help_text='Primary prompt body; supersedes content when present.'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
