# Generated by Django 5.2.6 on 2025-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptcenter', '0004_imageprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprompt',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
