# Generated by Django 5.2.6 on 2025-09-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptcenter', '0005_imageprompt_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVoteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(unique=True)),
                ('up_count', models.IntegerField(default=0)),
                ('down_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['image_id'], name='promptcente_image_id_idx')],
            },
        ),
    ]


