# Generated by Django 5.2.6 on 2025-09-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptcenter', '0006_imagevotecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('experience', 'Experience'), ('bug', 'Bug'), ('feature', 'Feature Request'), ('prompt_quality', 'Prompt Quality')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('reaction', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promptcenter.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='promptcente_categor_1e3f23_idx')],
            },
        ),
    ]


