# Generated by Django 5.2.6 on 2025-09-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptcenter', '0006_imagevotecounter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imagevotecounter',
            new_name='promptcente_image_i_cdb72c_idx',
            old_name='promptcente_image_id_idx',
        ),
    ]
