# Generated by Django 5.2.6 on 2025-09-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptcenter', '0007_feedback'),
        ('promptcenter', '0007_rename_promptcente_image_id_idx_promptcente_image_i_cdb72c_idx'),
    ]

    operations = [
    ]
