# Generated by Django 5.2.6 on 2025-09-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptcenter', '0008_merge_20250920_1736'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedback',
            new_name='promptcente_categor_72d935_idx',
            old_name='promptcente_categor_1e3f23_idx',
        ),
    ]
